name: Security Bot

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:

  run-bot:

    runs-on: ubuntu-latest # GitHub가 Ubuntu 서버 하나 만들어서 실행

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3 # GitHub repo 코드 다운로드
      with:
        token: ${{ secrets.GH_PAT }} # Cache 를 위한 키! 중복제거
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4 # Python 환경 자동 생성!
      with:
        python-version: "3.13"
# 필요한 Python 패키지 설치
    - name: Install packages
      run: |
        pip install -r requirements.txt

    - name: Run bot
      run: python bot.py
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_WEBHOOK_CVE: ${{ secrets.SLACK_WEBHOOK_CVE }}
    - name: Commit cache.json if changed
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add cache.json
        git diff --cached --quiet || git commit -m "Update cache.json"
        git push
